INSERT INTO `paper` VALUES ('dfg', '', 'null', 'null', 'null', 'null');
INSERT INTO `paper` VALUES ('fasfsdf', '', 'null', 'null', 'null', 'null');
INSERT INTO `paper` VALUES ('test', '', 'null', 'null', 'null', 'null');
INSERT INTO `paper` VALUES ('pppp', 'ooo', 'null', 'null', 'null', 'null');
INSERT INTO `paper` VALUES ('pppp', 'oooo', 'null', 'null', 'null', 'null');
INSERT INTO `paper` VALUES ('pppp', 'oooo', 'null', 'null', 'null', 'null');
INSERT INTO `paper` VALUES ('pppp', 'oooo', 'null', 'null', 'null', 'null');
INSERT INTO `paper` VALUES ('poiuytre', 'ertyui', 'null', 'null', 'null', 'null');
INSERT INTO `paper` VALUES ('你好我是论文', '哈尔滨工业大学', 'null', 'null', 'null', 'null');
INSERT INTO `paper` VALUES ('你好我是论文', '哈尔滨工业大学', 'null', 'null', 'null', 'null');
INSERT INTO `paper` VALUES ('发送到福', '曹德福', 'null', 'null', '阿斯顿发顺丰到付', 'null');
INSERT INTO `paper` VALUES ('发送到福', '曹德福', 'null', 'null', '阿斯顿发顺丰到付', 'null');
INSERT INTO `paper` VALUES ('舒服撒水电费', '的说法是打发发生的', 'null', 'null', '是打发斯蒂芬是打发斯蒂芬', 'null');
INSERT INTO `paper` VALUES ('舒服撒水电费', '的说法是打发发生的', 'null', 'null', '是打发斯蒂芬是打发斯蒂芬', 'null');
INSERT INTO `paper` VALUES ('dfg达哥', '上打广告方式', 'null', 'null', '是个大范甘迪发', 'null');
INSERT INTO `paper` VALUES ('dfg达哥', '上打广告方式', 'null', 'null', '是个大范甘迪发', '2016-11-07 20:27:04');
INSERT INTO `paper` VALUES ('dfg达哥否', '曹德福', 'null', 'null', '爱上对方法萨芬的', '2016-11-07 20:27:24');
INSERT INTO `paper` VALUES ('规范dfg达哥否', '哈尔滨工业大学', 'd:upload1140310115-Lab2-report.doc', 'null', '梵蒂冈和对方回复的恢复规划规范', '2016-11-07 20:31:47');
INSERT INTO `paper` VALUES ('bu规范dfg达哥否', '哈尔滨工业大学', 'd:upload1140310115-Lab2-report.doc', 'null', '梵蒂冈和对方回复的恢复规划规范', '2016-11-07 20:31:47');
INSERT INTO `paper` VALUES ('bu规范dfg达哥否', '哈尔滨工业大学', 'd:\\upload\\1140310115-Lab2-report.doc', 'null', '梵蒂冈和对方回复的恢复规划规范', '2016-11-07 20:31:47');
INSERT INTO `paper` VALUES ('规范dfg达哥否', '哈尔滨工业大学', 'd:/upload/1140310115-Lab2-report.doc', 'null', '梵蒂冈和对方回复的恢复规划规范', '2016-11-07 20:37:22');
INSERT INTO `paper` VALUES ('dfg达哥否否', '曹德福', 'd:/upload/1140310115-Lab2-report.doc', 'null', '阿斯顿发生打发打发', '2016-11-07 20:37:46');
